$route
 number-of-dimensions=1 space-dimension-1=r
$end
          
$nonstd
62//96;
20//01;
$end

$title
DVR Code
$end

$dimension-r
 number-of-regions=3 number-of-points-per-region=(10,10,10) 
 left-boundary-condition=0 right-boundary-condition=0
 region-boundaries=(0.d0,5.0d0,10.d0,15.d0)
$end

$v0-r
 use-atomic-units potential=exponential amplitude=-3.d0 
 exponent=1.d0
$end

$vpert
 potential=none a11=-3.d0 b11=1.d0
$end



