#                                                                                                                             
#
# Makefile for M0
#
include $(CURDIR)/dat
EXECUTABLE = $(MESA_BIN)/$(SOURCE)
ALL_INCLUDE = $(INCLUDE_LIST)
include $(MESA_HOME)/Makefile.inc
