/* mod_gen Version 1                                                     */
/* Module Name: "Write PPM" (Output) (Subroutine)                        */
/* Author: Tom Russo (T-12)                                              */
/* Date Created: Wed Mar 15 15:29:22 1995                                */
/*                                                                       */
/* This file is automatically generated by the Module Generator (mod_gen)*/
/* Please do not modify or move the contents of this comment block as    */
/* mod_gen needs it in order to read module sources back in.             */
/*                                                                       */
/* input 0 "image" field 2D 4-vector uniform byte REQUIRED               */
/* param 0 "PPM output file" browser "" "" ":"                           */
/* End of Module Description Comments                                    */

#include <stdio.h>
#include <avs/avs.h>
#include <avs/port.h>
#include <avs/field.h>
 
/* ----> START OF USER-SUPPLIED CODE SECTION #1 (INCLUDE FILES, GLOBAL VARIABLES)*/
static char file_version[]="write_ppm.c 03/15/95";

/* <---- END OF USER-SUPPLIED CODE SECTION #1                            */
 
/* *****************************************/
/*  Module Description                     */
/* *****************************************/
int Write_PPM_desc()
{

	int in_port, out_port, param;
	extern int Write_PPM_compute();

	AVSset_module_name("Write PPM", MODULE_RENDER);

	/* Input Port Specifications               */
	in_port = AVScreate_input_port("image", 
		"field 2D 4-vector uniform byte", REQUIRED);

	/* Parameter Specifications                */
	param = AVSadd_parameter("PPM output file", "string", " ", " ", ":");
	AVSconnect_widget(param, "browser");

	AVSset_compute_proc(Write_PPM_compute);
/* ----> START OF USER-SUPPLIED CODE SECTION #2 (ADDITIONAL SPECIFICATION INFO)*/
/* <---- END OF USER-SUPPLIED CODE SECTION #2                            */
	return(1);
}
 
/* *****************************************/
/* Module Compute Routine                  */
/* *****************************************/
int Write_PPM_compute( image, PPM_output_file)
	AVSfield_char *image;
	char *PPM_output_file;
{

/*  THIS IS A 'HINTS' AREA - YOU MAY CUT AND PASTE AT WILL FROM IT       */
/*                                                                       */
/* free any locally allocated data                                       */
/* THIS IS THE END OF THE 'HINTS' AREA. ADD YOUR OWN CODE BETWEEN THE    */
/* FOLLOWING COMMENTS. THE CODE YOU SUPPLY WILL NOT BE OVERWRITTEN.      */
 
/* ----> START OF USER-SUPPLIED CODE SECTION #3 (COMPUTE ROUTINE BODY)   */
  FILE *of;
  unsigned char *dat;
  int nx,ny,i,j,nchars,nc;

/* attempt to open file for write */
  if (!(of=fopen(PPM_output_file,"w")))
    {
      AVSmessage(file_version,AVS_Warning,NULL, "Write_PPM_compute",
		 "Ok", "Can't open output file %s",PPM_output_file);
      return(0);
    }

  fprintf(of,"P3\n");  /* PPM magic number */

  nx=MAXX(image);
  ny=MAXY(image);

  fprintf(of,"%d %d 255\n",nx,ny);

  for (i=0;i<ny;i++)
    {
      nchars=0;
      for (j=0;j<nx;j++)
	{
	  dat=I2DV(image,j,i);
	  fprintf(of,"%d %d %d %n",(int) dat[1],(int) dat[2],(int)dat[3],&nc);
	  if (nchars+nc >= 58)
	    {
	      nchars=0;
	      fprintf(of,"\n");
	    }
	  else
	    nchars += nc;
	}
      fprintf(of,"\n");
    }
  fclose(of);

/* <---- END OF USER-SUPPLIED CODE SECTION #3                            */
	return(1);
}
 
/* ***********************************************************************/
/* Initialization for modules contained in this file.                    */
/* ***********************************************************************/
int ((*mod_list[])()) = {
	Write_PPM_desc,
};
#define NMODS (sizeof(mod_list) / sizeof(char *))

AVSinit_modules()
{
	AVSinit_from_module_list(mod_list, NMODS);
}
 
/* ----> START OF USER-SUPPLIED CODE SECTION #4 (SUBROUTINES, FUNCTIONS, UTILITY ROUTINES)*/
/* <---- END OF USER-SUPPLIED CODE SECTION #4                            */
