#
#   @(#)Makefile	1.4   8/1/91
#
# Makefile for M940
#
include $(CURDIR)/dat
EXECUTABLE = $(MESA_BIN)/$(SOURCE)
SOURCE_LIB = $(LIBRARY)/$(SOURCE)lib.a
ALL_INCLUDE = $(INCLUDE_LIST)
include $(MESA_HOME)/Makefile.inc