#   @(#)Makefile	5.1 11/6/94
#
# Makefile for M930
#
SOURCE = m930
EXECUTABLE = $(MESA_BIN)/$(SOURCE)
GET = sccs get
REL = 

SRCS = \
	$(MESA_HOME)/$(SOURCE)/bscattr.f \
	$(MESA_HOME)/$(SOURCE)/bsort.f \
	$(MESA_HOME)/$(SOURCE)/getham.f \
	$(MESA_HOME)/$(SOURCE)/hqqsort.f \
	$(MESA_HOME)/$(SOURCE)/m930.f \
	$(MESA_HOME)/$(SOURCE)/matout.f \
	$(MESA_HOME)/$(SOURCE)/putham.f \
	$(MESA_HOME)/$(SOURCE)/pvcout.f \
	$(MESA_HOME)/$(SOURCE)/hamtest.f
ALL_INCLUDE = $(INCLUDE_LIST)
include $(MESA_HOME)/Makefile.inc