#   @(#)Makefile	5.2   4/18/95
#
# Makefile for $(SOURCE)
#

SOURCE=m201
EXECUTABLE = $(MESA_BIN)/$(SOURCE)
GET = sccs get
REL = 

SRCS = \
	$(MESA_HOME)/$(SOURCE)/bsinfo.f \
	$(MESA_HOME)/$(SOURCE)/bsinit.f \
	$(MESA_HOME)/$(SOURCE)/bslinr.f \
	$(MESA_HOME)/$(SOURCE)/bsmain.f \
	$(MESA_HOME)/$(SOURCE)/bsopt.f \
	$(MESA_HOME)/$(SOURCE)/bsquad.f \
	$(MESA_HOME)/$(SOURCE)/clnd2e.f \
	$(MESA_HOME)/$(SOURCE)/convgd.f \
	$(MESA_HOME)/$(SOURCE)/dfbydx.f \
	$(MESA_HOME)/$(SOURCE)/dxgrad.f \
	$(MESA_HOME)/$(SOURCE)/estmd2.f \
	$(MESA_HOME)/$(SOURCE)/fatx.f \
	$(MESA_HOME)/$(SOURCE)/fpderv.f \
	$(MESA_HOME)/$(SOURCE)/fpdump.f \
	$(MESA_HOME)/$(SOURCE)/fpexit.f \
	$(MESA_HOME)/$(SOURCE)/fphmat.f \
	$(MESA_HOME)/$(SOURCE)/fpinfo.f \
	$(MESA_HOME)/$(SOURCE)/fpinit.f \
	$(MESA_HOME)/$(SOURCE)/fpmain.f \
	$(MESA_HOME)/$(SOURCE)/fpsclt.f \
	$(MESA_HOME)/$(SOURCE)/fptest.f \
	$(MESA_HOME)/$(SOURCE)/gshmdt.f \
	$(MESA_HOME)/$(SOURCE)/lnrstp.f \
	$(MESA_HOME)/$(SOURCE)/$(SOURCE).f \
	$(MESA_HOME)/$(SOURCE)/msinfo.f \
	$(MESA_HOME)/$(SOURCE)/msinit.f \
	$(MESA_HOME)/$(SOURCE)/msmain.f \
	$(MESA_HOME)/$(SOURCE)/msopt.f \
	$(MESA_HOME)/$(SOURCE)/msstep.f \
	$(MESA_HOME)/$(SOURCE)/nrep.f \
	$(MESA_HOME)/$(SOURCE)/polfit.f \
	$(MESA_HOME)/$(SOURCE)/polmin.f \
	$(MESA_HOME)/$(SOURCE)/prmtbl.f \
	$(MESA_HOME)/$(SOURCE)/readfc.f \
	$(MESA_HOME)/$(SOURCE)/savept.f \
	$(MESA_HOME)/$(SOURCE)/updtd2.f
ALL_INCLUDE = $(INCLUDE_LIST)
include $(MESA_HOME)//Makefile.inc
