	#   @(#)Makefile	5.1   11/6/94
#
# Makefile for M822
#
SOURCE = m822
EXECUTABLE = $(MESA_BIN)/$(SOURCE)
GET = sccs get
REL = 

SRCS = \
	$(MESA_HOME)/$(SOURCE)/getdrt.f \
	$(MESA_HOME)/$(SOURCE)/$(SOURCE).f \
	$(MESA_HOME)/$(SOURCE)/srt2e.f \
	$(MESA_HOME)/$(SOURCE)/trn2e.f \
	$(MESA_HOME)/$(SOURCE)/vecout.f
ALL_INCLUDE = $(INCLUDE_LIST)
include $(MESA_HOME)/Makefile.inc
