#!/usr/bin/env python

import sys, os, shutil, glob

def usage():
    print "usage:", sys.argv[0], "directory"
    print "copies all files necessary for running TDCC_IT to directory"
    print "also includes source code and makefile etc."

if len(sys.argv)==1:
    usage()
    sys.exit(1)

progs=["TDCC_IT.exe",\
       "parameters.inp",\
       "regions.inp",\
       "tdcc_it.pbs"]

sources=glob.glob('*.f90')
sources.extend(["Makefile",\
                "Makefile.head",\
                "makeMakefile.py",\
                "makerun",\
                "setupvars32.sh",\
                "setupvars64.sh"])

targetdir=sys.argv[1]
srcdir=targetdir+"/src"

try:
    os.makedirs(srcdir)
except OSError, (errno, errstr):
    if (errno==17):
        while True:
            inp = raw_input("directory " + targetdir + " exists, overwrite? [y/n] ")
            if inp == "y" or inp == "Y":
                break
            if inp == "n" or inp == "N":
                sys.exit(2)
    else:
        raise

for finame in progs:
    shutil.copy2(finame,targetdir)

for finame in sources:
    shutil.copy2(finame,srcdir)

# maybe also write relevant shell variables to some file in the future
