$route
 number-of-dimensions=1 space-dimension-1=x
$end
          
$nonstd
63//00;
20//01;
$end

$title
DVR Code
$end

$h0(x)
 number-of-regions=2 
 polynomial-order-per-region=(15,15) number-of-fixed-points=2 
 region-boundaries=(0.d0,7.5d0,15.d0)
 left-fixed-point right-fixed-point print=all
 drop-first-function drop-last-function
$end

$v0(x)
 use-atomic-units potential=exponential 
 amplitude=-3.d0 exponent=1.d0
$end
